### ISSUE TITLE
React-native link error

### ISSUE THREAD

**Issue by Wellers0n** [react-native-community/async-storage#142]
Start link:
`react-native link @react-native-community/async-storage`

This error:
```
error Failed to get dependency config
debug Error: Failed to get dependency config
    at getDependencyConfig (/home/coffee/Documents/4Fun-Fullstack/node_modules/@react-native-community/cli/build/commands/link/getDependencyConfig.js:49:11)
    at Object.link [as func] (/home/coffee/Documents/4Fun-Fullstack/node_modules/@react-native-community/cli/build/commands/link/link.js:97:61)
    at Promise.resolve.then (/home/coffee/Documents/4Fun-Fullstack/node_modules/@react-native-community/cli/build/cliEntry.js:152:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by thymikee** [comment]
Hey @Wellers0n, we you'll find how to solve this issue here: https://github.com/react-native-community/cli/issues/273 :)
