### ISSUE TITLE
jest error while importing async storage

### ISSUE THREAD

**Issue by mbrucher** [react-native-community/async-storage#201]
## Current behavior

While running tests (`yarn test`) with a react native application, I get the following error message:

```sh
/node_modules/react-native/Libraries/Utilities/warnOnce.js:15
    const warnedKeys: {[string]: boolean} = {};
          ^^^^^^^^^^

    SyntaxError: Missing initializer in const declaration

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/react-native/Libraries/react-native/react-native-implementation.js:14:18)
```
## Expected behavior

I expect no errors

## Repro steps

I just import async-storage with the following `package.json`:

```json
  "jest": {
    "reporters": [
      "default",
      "jest-junit"
    ],
    "setupFiles": [
      "./src/__tests__/global.js"
    ],
    "modulePathIgnorePatterns": [
      "global.js"
    ],
    "coverageReporters": [
      "html",
      "cobertura"
    ],
    "moduleNameMapper": {
      "\\.(css|less|sass|scss)$": "<rootDir>/src/__mocks__/styleMock.js",
      "\\.(gif|ttf|eot|svg)$": "<rootDir>/src/__mocks__/fileMock.js"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!(.*async-storage.*)/)"
    ],
    "preset": "react-native"
  },
```
## Environment

- **Async Storage version**: 1.6.1
- **React-Native version**: 0.60.5
- **Platform tested**: MacOS

**Comment by Krizzu** [comment]
@mbrucher [Have you seen Jest integration docs?](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md)

**Comment by mbrucher** [comment]
Probably... It's so annoying to have to deal with all these issues in JS.

**Comment by leotm** [comment]
New URL: https://github.com/invertase/react-native-async-storage/blob/master/docs/Jest-integration.md
