### ISSUE TITLE
Android app crashes with @next version using legacy storage + async storage factory

### ISSUE THREAD

**Issue by pedroSoaresll** [react-native-community/async-storage#288]
## Current behavior
```
2020-01-31 15:07:05.759 1876-1890/? E/memtrack: Couldn't load memtrack module
2020-01-31 15:07:05.780 1876-1890/? E/memtrack: Couldn't load memtrack module
2020-01-31 15:07:05.792 1876-1890/? E/memtrack: Couldn't load memtrack module
2020-01-31 15:07:05.815 19696-19703/? E/nearhairstylis: Failed to send DDMS packet REAQ to debugger (-1 of 20): Broken pipe
2020-01-31 15:07:05.940 19696-19696/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nearhairstylist, PID: 19696
    java.lang.RuntimeException: Unable to instantiate application com.nearhairstylist.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.nearhairstylist.MainApplication" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nearhairstylist-kgMTjlPFrr9NPzVk6nlcPg==/base.apk"],nativeLibraryDirectories=[/data/app/com.nearhairstylist-kgMTjlPFrr9NPzVk6nlcPg==/lib/x86_64, /data/app/com.nearhairstylist-kgMTjlPFrr9NPzVk6nlcPg==/base.apk!/lib/x86_64, /system/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1069)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.nearhairstylist.MainApplication" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.nearhairstylist-kgMTjlPFrr9NPzVk6nlcPg==/base.apk"],nativeLibraryDirectories=[/data/app/com.nearhairstylist-kgMTjlPFrr9NPzVk6nlcPg==/lib/x86_64, /data/app/com.nearhairstylist-kgMTjlPFrr9NPzVk6nlcPg==/base.apk!/lib/x86_64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1120)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1061)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5842) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2020-01-31 15:07:06.062 2588-18576/? E/s.nexuslaunche: No package ID ff found for ID 0xffffffff.
2020-01-31 15:07:06.063 2588-18576/? E/IconLoader: Could not find icon drawable from resource
    android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
        at android.content.res.Resources.getDrawable(Resources.java:827)
        at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(SourceFile:118)
        at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(SourceFile:94)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(SourceFile:325)
        at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(SourceFile:188)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(SourceFile:173)
        at com.android.quickstep.RecentsModel.onTaskStackChangedBackground(SourceFile:214)
        at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(SourceFile:80)
        at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
        at android.os.Binder.execTransact(Binder.java:731)
2020-01-31 15:07:06.602 1726-2731/? E/IPCThreadState: binder thread pool (4 threads) starved for 115 ms
```

## Expected behavior
I expected that app opens

## Repro steps
1. install this version from package
```json
"@react-native-community/async-storage": "^2.0.0-rc.1",
"@react-native-community/async-storage-backend-legacy": "^2.0.0-rc.1",
```
2. run ```yarn android``` and start metro server
3. try open app, it will crashes before open :cry: 

## Environment

- **Async Storage version**: 
- **React-Native version**: 
- **Platform tested**: 
- **Logs/Error that are relevant**: 

## This is my complete package JSON
```json
{
  "name": "AppCabeleireiro",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "emulator": "emulator -avd Nexus_5X_API_29_x86",
    "proxy": "adb reverse tcp:9090 tcp:9090 && adb reverse tcp:3001 tcp:3001"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^2.0.0-rc.1",
    "@react-native-community/async-storage-backend-legacy": "^2.0.0-rc.1",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/google-signin": "^3.0.4",
    "@react-native-community/masked-view": "^0.1.6",
    "axios": "^0.19.1",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-maps": "^0.26.1",
    "react-native-modal": "^11.5.3",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.6.2",
    "react-native-screens": "^2.0.0-alpha.25",
    "react-navigation": "^4.1.0",
    "react-navigation-stack": "^2.0.16",
    "reactotron-react-native": "^4.0.3",
    "socket.io": "^2.3.0",
    "styled-components": "^5.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "eslint-plugin-react-hooks": "^2.3.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by Krizzu** [comment]
@pedroSoaresll 

Seems like your issue is more related to your Android app than having Async Storage installed.

java.lang.RuntimeException: **Unable to instantiate application com.nearhairstylist.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.nearhairstylist.MainApplication"** on path:
