### ISSUE TITLE
'AsyncStorage.web.js: Unexpected token, expected ";" (21:42)'

### ISSUE THREAD

**Issue by csaar95** [react-native-community/async-storage#356]
## Current behavior

I can't use any `AsyncStorage` functionality.
I'm not very familiar with node, so maybe it's an error caused by me. But didn't found anything similar.

## Repro steps

- `npm install @react-native-community/async-storage`

```typescript
import AsyncStorage from '@react-native-community/async-storage';

[...]

const Casy = {
  async login(apiToken: string) {
    await AsyncStorage.setItem('token', apiToken);
  },

[...]

};

export default Casy;
```

## Environment

- **Async Storage version**:  ^1.10.0
- **React-Native version**: -
- **Babel-Loader version**: 8.1.0
- **Ionic version**: CLI 6.6.0
- **Platform tested**: Chrome
- **Logs/Error that are relevant**: 
```
index.ts:53 Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\Christian\scripts\ionic\casy-time-tracking\node_modules\@react-native-community\async-storage\lib\AsyncStorage.web.js: Unexpected token, expected ";" (21:42)

  19 | };
  20 | 
> 21 | const createPromise = (getValue, callback): Promise<*> => {
     |                                           ^
  22 |   return new Promise((resolve, reject) => {
  23 |     try {
  24 |       const value = getValue();
    at Parser._raise (C:\Users\Christian\scripts\ionic\casy-time-tracking\node_modules\@babel\parser\lib\index.js:742:17)
    at Parser.raiseWithData (C:\Users\Christian\scripts\ionic\casy-time-tracking\node_modules\@babel\parser\lib\index.js:735:17)
    at Parser.raise (C:\Users\Christian\scripts\ionic\casy-time-tracking\node_modules\@babel\parser\lib\index.js:729:17)
    at Parser.unexpected (C:\Users\Christian\scripts\ionic\casy-time-tracking\node_modules\@babel\parser\lib\index.js:8757:16)
    at Parser.semicolon (C:\Users\Christian\scripts\ionic\casy-time-tracking\node_modules\@babel\parser\lib\index.js:8739:40)
    at Parser.parseVarStatement (C:\Users\Christian\scripts\ionic\casy-time-tracking\node_modules\@babel\parser\lib\index.js:11550:10)
    at Parser.parseStatementContent (C:\Users\Christian\scripts\ionic\casy-time-tracking\node_modules\@babel\parser\lib\index.js:11148:21)
    at Parser.parseStatement (C:\Users\Christian\scripts\ionic\casy-time-tracking\node_modules\@babel\parser\lib\index.js:11081:17)
    at Parser.parseBlockOrModuleBlockBody (C:\Users\Christian\scripts\ionic\casy-time-tracking\node_modules\@babel\parser\lib\index.js:11656:25)
    at Parser.parseBlockBody (C:\Users\Christian\scripts\ionic\casy-time-tracking\node_modules\@babel\parser\lib\index.js:11642:10)
    at Object../node_modules/@react-native-community/async-storage/lib/AsyncStorage.web.js (http://localhost:8100/static/js/78.chunk.js:10026:7)
    at __webpack_require__ (http://localhost:8100/static/js/bundle.js:790:30)
    at fn (http://localhost:8100/static/js/bundle.js:151:20)
    at Module../node_modules/@react-native-community/async-storage/lib/index.js (http://localhost:8100/static/js/78.chunk.js:10050:71)
    at __webpack_require__ (http://localhost:8100/static/js/bundle.js:790:30)
    at fn (http://localhost:8100/static/js/bundle.js:151:20)
    at Module../src/util/Casy.ts (http://localhost:8100/static/js/main.chunk.js:2468:95)
    at __webpack_require__ (http://localhost:8100/static/js/bundle.js:790:30)
    at fn (http://localhost:8100/static/js/bundle.js:151:20)
    at Module../src/pages/Home.tsx (http://localhost:8100/static/js/main.chunk.js:2056:68)
    at __webpack_require__ (http://localhost:8100/static/js/bundle.js:790:30)
    at fn (http://localhost:8100/static/js/bundle.js:151:20)
    at Module../src/App.tsx (http://localhost:8100/static/js/main.chunk.js:535:69)
    at __webpack_require__ (http://localhost:8100/static/js/bundle.js:790:30)
    at fn (http://localhost:8100/static/js/bundle.js:151:20)
    at Module../src/index.tsx (http://localhost:8100/static/js/main.chunk.js:1962:62)
    at __webpack_require__ (http://localhost:8100/static/js/bundle.js:790:30)
    at fn (http://localhost:8100/static/js/bundle.js:151:20)
    at Object.1 (http://localhost:8100/static/js/main.chunk.js:2689:18)
    at __webpack_require__ (http://localhost:8100/static/js/bundle.js:790:30)
    at checkDeferredModules (http://localhost:8100/static/js/bundle.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://localhost:8100/static/js/bundle.js:33:19)
    at http://localhost:8100/static/js/main.chunk.js:1:89
```

**Comment by csaar95** [comment]
Please delete this, I'm not using react-native.... sry

**Comment by Krizzu** [comment]
@csaar95 AsyncStorage has support for web.

The new version should fix what you see. I'm going to release new version soon.
