### ISSUE TITLE
defined multiple times

### ISSUE THREAD

**Issue by RicardoDolNL** [react-native-community/async-storage#390]
## Current behavior

I get a error while building a release for android:
`Error: /my-app/node_modules/@react-native-community/async-storage/android/build/.transforms/fc2daeb4ff0db30fd0f1f5e68862f91b/classes/classes.dex, Type com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil is defined multiple times: /my-app/node_modules/@react-native-community/async-storage/android/build/.transforms/fc2daeb4ff0db30fd0f1f5e68862f91b/classes/classes.dex, /my-app/android/app/build/intermediates/external_libs_dex/release/out/classes2.dex
`

Already did ./gradlew clean

## Expected behavior

That I can build my release.

## Environment

- **Async Storage version**:  1.11.0
- **React-Native version**: 0.62.2
- **Platform tested**: Android
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
Seems like Gradle issue or Async Storage added twice somehow. Did you try removing `node_modules` and installing them again?

**Comment by RicardoDolNL** [comment]
Yes i know, it does look that way. Is it possible that another dependency also makes use of async storage and that that is the conflict here? And yes i did remove the node_modules map already.

**Comment by Krizzu** [comment]
> Yes i know, it does look that way. Is it possible that another dependency also makes use of async storage and that that is the conflict here? And yes i did remove the node_modules map already.

I don't see third party involved here:

```
/my-app/node_modules/@react-native-community/async-storage/android/build/.transforms/fc2daeb4ff0db30fd0f1f5e68862f91b/classes/classes.dex
/my-app/android/app/build/intermediates/external_libs_dex/release/out/classes2.dex
```

With RN 0.62, I believe you let `auto-linking` link the library for you? What about removing `node_modules/@react-native-community/async-storage/android/build` and `/my-app/android/app/build` by hand and trying again?

**Comment by RicardoDolNL** [comment]
I did use auto-linking yes.
Removing those folders by hand and building bundle release failed again. Same error.

**Comment by Krizzu** [comment]
That's very possible that one of your native dependency lib has dependency on AsyncStorage (and include it in their build), hence collision (which is really uncool for the lib itself - it should mention that it requires AS as dependency and should be added by user).

**Comment by RicardoDolNL** [comment]
Adding this line fixed my problem `exclude group: 'com.facebook.react',module:'react-native-community-async-storage'` within react-natvie-jitsi-meet. So it was more a problem because of that dependency.

```
implementation(project(':react-native-jitsi-meet')) {
        exclude group: 'com.facebook.react',module:'react-native-svg'
        exclude group: 'com.facebook',module:'hermes'
        exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
    }

    implementation ('org.jitsi.react:jitsi-meet-sdk:2.8.2') {
        exclude group: 'com.facebook.react',module:'react-native-svg'
        exclude group: 'com.facebook',module:'hermes'
        exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
        transitive = true
    }
```

**Comment by Krizzu** [comment]
Glad you have it worked out.

**Comment by anshumanburman** [comment]
@RicardoDolNL this issue is fixed i thing but it is giving another error like below. If you have any idea please tell me.

`Type co.apptailor.googlesignin.BuildConfig is defined multiple times: /Users/ansh/Documents/ANSH/FitnerApp/node_modules/@react-native-community/google-signin/android/build/.transforms/985c9104e7fdec208675d8ebe3e42604/classes/classes.dex, /Users/ansh/Documents/ANSH/FitnerApp/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes.dex`

**Comment by focalsolution** [comment]
@RicardoDolNL When I exclude AsyncStorage, the Release can build properly. However, jitsi will throw exception at runtime. For example, when it tried to open Video call.

Not quite sure if you face similar issue and how you resolved it.
Can you shine me some light?

**Comment by RicardoDolNL** [comment]
> @RicardoDolNL this issue is fixed i thing but it is giving another error like below. If you have any idea please tell me.
> 
> `Type co.apptailor.googlesignin.BuildConfig is defined multiple times: /Users/ansh/Documents/ANSH/FitnerApp/node_modules/@react-native-community/google-signin/android/build/.transforms/985c9104e7fdec208675d8ebe3e42604/classes/classes.dex, /Users/ansh/Documents/ANSH/FitnerApp/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes.dex`

Sounds like a similar problem. You cloud try also excluding it, something like this:
``exclude group: 'com.facebook.react',module:'react-native-community-google-signin'``

But i don't know if it's a conflict with jitsi-meet, so you might need to exclude it for an other implementation.
I also saw somewhere that settting multiDexEnabled to true (in app/build.gradle defaultConfig) might also fix it.
```
defaultConfig {
        ...the rest of you default config
        multiDexEnabled true
    }
```

**Comment by RicardoDolNL** [comment]
> @RicardoDolNL When I exclude AsyncStorage, the Release can build properly. However, jitsi will throw exception at runtime. For example, when it tried to open Video call.
> 
> Not quite sure if you face similar issue and how you resolved it.
> Can you shine me some light?

As far as i know i didn't had that problem. You might want to ask around at https://github.com/skrafft/react-native-jitsi-meet for that (since i'm guessing you're using that dependancy?)

**Comment by muganwas** [comment]
Had the same issue, I unlinked the package `react-native unlink @react-native-community/async-storage`, upgraded it to the latest version, rebuilt my project Build > Rebuild Project. Runs perfectly now.

**Comment by mAnasAwan** [comment]
In my case, i had two AsyncStorage packages installed i.e 

> **@react-native-async-storage/async-storage**

> **@react-native-community/async-storage**

uninstalling/removing one of the package would give you module not found error, as some of other packages like @aws-amplify,@aws-sdk etc were importing AsyncStorage from either of two packages in **node_modules/${packageName}/core/lib-esm/StorageHelper/reactnative.js**

- [ ] just use single common **import AsyncStorage from** statement in all of your packages file as well as in your project files its either from **@react-native-async-storage/async-storage** in all or **@react-native-community/async-storage** in all, use find and replace feature of your editor
- [ ] remove package whose Import instance is 0 
- [ ] rebuild project

![Screenshot 2021-05-21 at 6 49 13 PM](https://user-images.githubusercontent.com/50512005/119147706-4494d580-ba65-11eb-80a1-1a748ca7259f.png)

**Comment by aaryavrate** [comment]
I am having a similar problem, but none of the above solutions worked. 

Error:

```
Type com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil is defined multiple times: /repo/node_modules/@react-native-async-storage/async-storage/android/build/.transforms/663cdbfa6251d6d0169ee25e741ce1cd/classes/classes.dex, /repo/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes3.dex

```


```

dependencies {
    implementation(project(':react-native-jitsi-meet')) {
        exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
        exclude group: 'com.facebook.react',module:'react-native-svg'
                transitive = true
    }
.....

```

**Comment by aaryavrate** [comment]
I have latest v 16 of @react-native-async-storage. In the node-modules folder, I find that this repo as react-native-community-async-storage
Is that a reason for this duplicacy?

**Comment by Zontex** [comment]
> eact-native-community-async-storage

This issue is because react-native-community-async-storage is deprecated, remove it and use async storage instead.

**Comment by Nulll-cyber** [comment]
Actually it work for me 😁
uninstall package . and reinstall it @react-native-async-storage/async-storage or which ever you have install.
`yarn remove @react-native-async-storage/async-storage
`

again install `yarn  add @react-native-async-storage/async-storage
`
in my case it work

**Comment by oscarrock** [comment]
Hey guys i have tryed several things for my project i still got this issue

This is my package.json

`"@react-native-async-storage/async-storage": "^1.18.1",
    "@react-native-community/datetimepicker": "^3.0.4",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/netinfo": "^9.3.8",
    "@react-native-community/push-notification-ios": "^1.7.1",
    "@react-native-firebase/app": "^17.4.0",
    "@react-native-firebase/messaging": "^17.4.0",
    "@react-native-masked-view/masked-view": "^0.2.9",
    "add": "^2.0.6",
    "fbemitter": "^2.1.1",
    "install": "^0.13.0",
    "lottie-ios": "3.2.3",
    "lottie-react-native": "^4.0.3",
    "md5": "^2.3.0",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.31",
    "react": "18.2.0",
    "react-google-maps": "^9.4.5",
    "react-moment": "^1.0.0",
    "react-native": "^0.71.5",
    "react-native-animatable": "^1.3.3",
    "react-native-device-info": "^10.5.1",
    "react-native-fast-image": "^8.3.2",
    "react-native-geolocation-service": "^5.0.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-gifted-chat": "^1.0.0",
    "react-native-google-static-map": "^0.1.13",
    "react-native-image-picker": "^4.7.3",
    "react-native-jitsi-meet": "^2.1.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-maps": "^1.4.0",
    "react-native-material-dropdown-v2": "^0.11.1",
    "react-native-modal-datetime-picker": "^9.0.0",
    "react-native-multiple-select": "https://github.com/oscarrock/react-native-multiple-select",
    "react-native-pager-view": "^6.2.0",
    "react-native-paper": "^4.2.0",
    "react-native-pose": "^0.9.1",
    "react-native-push-notification": "^7.3.1",
    "react-native-reanimated": "^3.0.0-rc.3",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-sound": "^0.11.0",
    "react-native-spinkit": "^1.5.1",
    "react-native-svg": "^12.1.0",
    "react-native-svg-uri": "^1.2.3",
    "react-native-uuid-generator": "^6.1.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-view-shot": "^3.1.2",
    "react-native-webview": "^11.10.0",
    "react-navigation": "^4.4.3",
    "react-navigation-material-bottom-tabs": "^2.3.3",
    "react-navigation-stack": "^2.9.0",
    "react-navigation-tabs": "^2.10.1",
    "rn-fetch-blob": "^0.12.0",
    "sync-storage": "^0.4.2"
`
My android/app/build.gradle

`

 implementation(project(':react-native-jitsi-meet')) {
      exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
      exclude group: 'com.facebook.react',module:'@react-native-community-async-storage/async-storage'
      exclude group: 'com.facebook.react' ,module: 'react-native-locale-detector'
      exclude group: 'com.facebook.react', module: 'react-native-vector-icons'
      exclude group: 'com.facebook', module: 'hermes'
      exclude group: 'com.facebook.react', module: 'react-native-community-async-storage'
      exclude group: 'com.facebook.react', module: 'react-native-community_netinfo'
      exclude group: 'com.facebook.react', module: 'react-native-svg'
      exclude group: 'com.facebook.react', module: 'react-native-fetch-blob'
      exclude group: 'com.facebook.react', module: 'react-native-webview'
      exclude group: 'com.facebook.react', module: 'react-native-linear-gradient'
      exclude group: 'com.facebook.react', module: 'react-native-sound'
      exclude group: 'com.facebook.react', module: 'react-native-reanimated'
      exclude group: 'com.facebook.react', module: 'react-native-device-info'
      exclude group: 'com.facebook.react', module: 'react-native-pager-view'
      exclude group: 'com.facebook.react', module: 'react-native-gesture-handler'
      exclude group: 'com.facebook.react', module: 'react-native-screens'
      exclude group: 'com.facebook.react', module: 'react-native-safe-area-context'
      exclude group: 'com.facebook.react', module: 'react-native-masked-view_masked-view'
    }

      implementation ('org.jitsi.react:jitsi-meet-sdk:5.1.0') {
        exclude group: 'com.facebook.react', module:'react-native-community-async-storage'
        exclude group: 'com.facebook.react',module:'@react-native-community-async-storage/async-storage'
        exclude group: 'com.facebook.react' ,module: 'react-native-locale-detector'
        exclude group: 'com.facebook.react', module: 'react-native-vector-icons'
        exclude group: 'com.facebook', module: 'hermes'
        exclude group: 'com.facebook.react', module: 'react-native-community-async-storage'
        exclude group: 'com.facebook.react', module: 'react-native-community_netinfo'
        exclude group: 'com.facebook.react', module: 'react-native-svg'
        exclude group: 'com.facebook.react', module: 'react-native-fetch-blob'
        exclude group: 'com.facebook.react', module: 'react-native-webview'
        exclude group: 'com.facebook.react', module: 'react-native-linear-gradient'
        exclude group: 'com.facebook.react', module: 'react-native-sound'
        exclude group: 'com.facebook.react', module: 'react-native-reanimated'
        exclude group: 'com.facebook.react', module: 'react-native-device-info'
        exclude group: 'com.facebook.react', module: 'react-native-pager-view'
        exclude group: 'com.facebook.react', module: 'react-native-gesture-handler'
        exclude group: 'com.facebook.react', module: 'react-native-screens'
        exclude group: 'com.facebook.react', module: 'react-native-safe-area-context'
        exclude group: 'com.facebook.react', module: 'react-native-masked-view_masked-view'
        exclude group: 'com.facebook',module:'hermes'
        transitive = true
    }

`

and this is stack trace of the error. It only ocurrs on assembleRelease. On debugging is working fine.
I had to disable hermes becouse react native jisti meet is crashing with it

` Task :app:mergeDexRelease
ERROR:/home/app/node_modules/@react-native-async-storage/async-storage/android/build/.transforms/0f9967cfb27ce2a978360436798231ac/transformed/classes/classes.dex: D8: Type com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil is defined multiple times: /home/app/node_modules/@react-native-async-storage/async-storage/android/build/.transforms/0f9967cfb27ce2a978360436798231ac/transformed/classes/classes.dex, /home/app/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes3.dex
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil is defined multiple times: /home/app/node_modules/@react-native-async-storage/async-storage/android/build/.transforms/0f9967cfb27ce2a978360436798231ac/transformed/classes/classes.dex, /home/app/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes3.dex
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:151)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:138)
        at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:859)
        at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:805)
        at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
        at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:205)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:187)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:120)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:162)
        at org.gradle.internal.Factories$1.create(Factories.java:31)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
        at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:114)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:157)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:126)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /home/app/node_modules/@react-native-async-storage/async-storage/android/build/.transforms/0f9967cfb27ce2a978360436798231ac/transformed/classes/classes.dex
        at Version.fakeStackEntry(Version_3.3.83.java:0)
        at com.android.tools.r8.internal.Hj.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:75)
        at com.android.tools.r8.internal.Hj.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:28)
        at com.android.tools.r8.internal.Hj.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:27)
        at com.android.tools.r8.internal.Hj.b(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:2)
        at com.android.tools.r8.D8.run(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:11)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:136)
        ... 38 more
Caused by: com.android.tools.r8.internal.f: Type com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil is defined multiple times: /home/app/node_modules/@react-native-async-storage/async-storage/android/build/.transforms/0f9967cfb27ce2a978360436798231ac/transformed/classes/classes.dex, /home/app/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes3.dex
        at com.android.tools.r8.internal.LT.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:14)
        at com.android.tools.r8.internal.LT.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:22)
        at com.android.tools.r8.internal.JN.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:36)
        at com.android.tools.r8.internal.JN.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:10)
        at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
        at com.android.tools.r8.internal.JN.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:6)
        at com.android.tools.r8.graph.B2$a.e(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:7)
        at com.android.tools.r8.dex.b.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:101)
        at com.android.tools.r8.dex.b.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:25)
        at com.android.tools.r8.dex.b.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:24)
        at com.android.tools.r8.D8.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:25)
        at com.android.tools.r8.D8.d(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:606)
        at com.android.tools.r8.D8.b(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:1)
        at com.android.tools.r8.internal.Hj.a(R8_3.3.83_3e328a3bbd0c840823c96123eb0f6192f0adf17b30ae46f695be39af0bc3505e:24)
        ... 41 more


> Task :app:mergeDexRelease FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDexRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction`
