### ISSUE TITLE
Android issue when upgrading to react-native 0.63.0 (NoSuchMethodError)

### ISSUE THREAD

**Issue by lmarques6** [react-native-community/async-storage#432]
## Current behavior

Async Storage crashes the Android app when used with React-Native version 0.63.0 .

## Expected behavior

Async Storage should not to crash the application, and work as expected. Issue does not occur on iOS.

## Repro steps

Upgrade to RN 0.63.0 and attempt to use async storage. You will see a crash when Async Storage passes through a WritableArray instead of a ReadableArray. Can best be seen when running via Android Studio.

## Environment

- **Async Storage version**: 1.12.0
- **React-Native version**:0.63.0
- **Platform tested**: Android
- **Logs/Error that are relevant**: 
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at com.reactnativecommunity.asyncstorage.AsyncStorageModule$SerialExecutor$1.run(AsyncStorageModule.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NoSuchMethodError: No interface method pushArray(Lcom/facebook/react/bridge/ReadableArray;)V in class Lcom/facebook/react/bridge/WritableArray; or its super classes (declaration of 'com.facebook.react.bridge.WritableArray' appears in /data/app/com.app.debug-Th_iWMe_RSrq4LzdIkXKLA==/base.apk)
        at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded(AsyncStorageModule.java:183)
        at com.reactnativecommunity.asyncstorage.AsyncStorageModule$1.doInBackgroundGuarded(AsyncStorageModule.java:132)
        at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:32)
        at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:20)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.reactnativecommunity.asyncstorage.AsyncStorageModule$SerialExecutor$1.run(AsyncStorageModule.java:62) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by lmarques6** [comment]
Seems like I ran into some issues with react-native version upgrade due to a different package that needed updating (react-native-v8). No issue here.

**Comment by SudoPlz** [comment]
@lmarques6 can you explain a bit further what the issue was here?
We're getting the same crash in production but can't seem to figure this out (we're not using react-native-v8)

**Comment by lmarques6** [comment]
Hi @SudoPlz , it seems like your error is caused by an `OutOfMemoryError` rather than a `NoSuchMethodError`. My problem occurred because the `react-native-v8` package was overriding my `react-native` module, keeping it at an outdated version, even though I had upgraded `react-native`.
